name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 0.8.0, leave empty to use Cargo.toml version)"
        required: false
        type: string
      skip_tests:
        description: "Skip tests before building"
        required: false
        default: false
        type: boolean
      create_tag:
        description: "Create and push git tag"
        required: false
        default: true
        type: boolean
      create_github_release:
        description: "Create GitHub Release"
        required: false
        default: true
        type: boolean

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !inputs.skip_tests)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-ubuntu"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libinput-dev libxdo-dev

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test before release
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 15
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !inputs.skip_tests)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-ubuntu"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libinput-dev libxdo-dev

      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: [lint, test]
    if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped') && (needs.test.result == 'success' || needs.test.result == 'skipped')
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: gestures
            asset_name: gestures-linux-x86_64
            container: quay.io/pypa/manylinux2014_x86_64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            artifact_name: gestures
            asset_name: gestures-linux-aarch64
            container: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version if specified
        if: github.event.inputs.version != ''
        run: |
          VERSION="${{ github.event.inputs.version }}"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          echo "Updated version to $VERSION"

      - name: Make build script executable
        if: matrix.container != ''
        run: chmod +x .github/scripts/build-linux.sh

      - name: Set up Docker cache directories
        if: matrix.container != ''
        run: |
          mkdir -p ~/.cargo-cache
          mkdir -p ~/.rustup-cache

      - name: Cache Rust toolchain and dependencies (Docker)
        if: matrix.container != ''
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo-cache
            ~/.rustup-cache
          key: ${{ runner.os }}-manylinux-rust-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-manylinux-rust-${{ matrix.target }}-
            ${{ runner.os }}-manylinux-rust-

      - name: Build in manylinux container
        if: matrix.container != ''
        run: |
          docker run --rm \
            -v "$(pwd)":/workspace \
            -v "$HOME/.cargo-cache":/rust/cargo \
            -v "$HOME/.rustup-cache":/rust/rustup \
            -w /workspace \
            -e TARGET=${{ matrix.target }} \
            -e ASSET_NAME=${{ matrix.asset_name }} \
            -e CARGO_HOME=/rust/cargo \
            -e RUSTUP_HOME=/rust/rustup \
            ${{ matrix.container }} \
            /workspace/.github/scripts/build-linux.sh

      # Native ARM64 build (no container)
      - name: Install Rust toolchain (native)
        if: matrix.container == ''
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache (native)
        if: matrix.container == ''
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-${{ matrix.target }}"

      - name: Install system dependencies (native)
        if: matrix.container == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libinput-dev libxdo-dev

      - name: Build release (native)
        if: matrix.container == ''
        run: |
          cargo build --release --target ${{ matrix.target }} --verbose
          strip target/${{ matrix.target }}/release/gestures
          cd target/${{ matrix.target }}/release
          tar czf ${{ matrix.asset_name }}.tar.gz gestures
          mv ${{ matrix.asset_name }}.tar.gz ../../..
          ls -lh ../../../${{ matrix.asset_name }}.tar.gz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}.tar.gz
          if-no-files-found: error

  create-tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.create_tag == 'true' && github.event.inputs.version != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          VERSION="${{ github.event.inputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin "v${VERSION}"
          echo "Created and pushed tag v${VERSION}"

  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: always() && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_github_release == 'true')) && needs.build.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Extract version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.version }}" ]; then
              VERSION="${{ github.event.inputs.version }}"
            else
              VERSION=$(grep '^version =' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
            fi
            TAG="v${VERSION}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Version: $VERSION, Tag: $TAG"

      - name: Ensure tag exists
        run: |
          TAG="${{ steps.get_version.outputs.tag }}"
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG does not exist, creating it..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
            echo "Created and pushed tag $TAG"
          else
            echo "Tag $TAG already exists"
          fi

      - name: Generate changelog
        id: changelog
        run: |
          TAG="${{ steps.get_version.outputs.tag }}"
          PREV_TAG=$(git describe --tags --abbrev=0 "$TAG^" 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            CHANGELOG=$(git log ${PREV_TAG}..${TAG} --pretty=format:"- %s (%h)" --no-merges)
          fi

          echo "$CHANGELOG" > changelog.txt

          {
            echo 'changelog<<EOF'
            echo "$CHANGELOG"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f -name "*.tar.gz" -exec cp {} release-assets/ \;
          ls -lh release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          name: Release ${{ steps.get_version.outputs.tag }}
          body_path: changelog.txt
          files: release-assets/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
